name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.7
    with:
      number-of-agents: 3
      parallel-commands: |
        pnpm nx-cloud record -- pnpm nx workspace-lint
        pnpm nx-cloud record -- pnpm nx format:check
      parallel-commands-on-agents: |
        pnpm nx affected --target=lint --parallel=3
        pnpm nx affected --target=test --parallel=3 --ci --code-coverage
        pnpm nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.7
    with:
      number-of-agents: 3